/**
 * scenarioService.js — Scenario generation for the Social Scenario Simulator.
 *
 * One defined situation, one role, one response. Scenarios are generated by
 * Gemini through the shared AI facade when available and always fall back to a
 * deterministic, rotating library so repeated sessions stay varied. The module
 * never stores raw audio; history keeps scores and titles only.
 */

import {
  SCENARIO_ATTEMPTS_STORAGE_KEY,
  SCENARIO_CATEGORY_IDS,
  SCENARIO_DIFFICULTY_IDS,
  SOCIAL_SCENARIO_MODULE_ID,
  getScenarioCategoryById,
  getScenarioDifficultyById,
} from "./socialScenarioTypes";
import { generateSocialScenario as callAiGenerateScenario } from "@/features/socialCommunication/services/aiService";

/** Deterministic fallback pool. Each item is a single-response scenario:
 *  a situation, the user's role, what the other person says, observable cues,
 *  and one example good response. Never shames; always practical. */
export const FALLBACK_SCENARIOS = Object.freeze([
  // ── COLLEGE ──
  {
    id: "college.interrupting-classmate",
    category: "college",
    difficulty: "easy",
    title: "Interrupting a Classmate",
    setting: "A small group is planning a project in the library.",
    situation:
      "You accidentally start talking while Maya is explaining her part of the project plan.",
    role: "You are part of the group.",
    question: "Maya stops mid-sentence and looks at you. What do you say?",
    cues: ["Maya stopped mid-sentence", "She is looking at you", "The group has gone quiet"],
    suggestedResponse: "Sorry — go ahead, Maya. I'll wait until you are finished.",
    hint: "A short apology and handing the turn back is enough.",
  },
  {
    id: "college.misunderstanding-deadline",
    category: "college",
    difficulty: "medium",
    title: "Checking a Deadline",
    setting: "After a lecture, your tutor is packing up.",
    situation:
      "You think the assignment is due next week, but someone said it is due on Friday. You are not sure.",
    role: "You are a student.",
    question: "Your tutor looks up as you approach. What do you say?",
    cues: [
      "The tutor is in a hurry",
      "You are not sure about the date",
      "Getting it wrong would cause stress",
    ],
    suggestedResponse: "Excuse me — could you confirm when the assignment is due? I want to make sure I have the right date.",
    hint: "It helps to say exactly what you are unsure about.",
  },
  {
    id: "college.group-work-disagree",
    category: "college",
    difficulty: "hard",
    title: "Disagreeing in Group Work",
    setting: "Your group is choosing a presentation topic.",
    situation:
      "Two group members want to cover a topic you already researched, but you think the class heard enough about it.",
    role: "You are in the group.",
    question: "Everyone turns to you for your opinion. What do you say?",
    cues: [
      "The group is waiting for your opinion",
      "Two members already agree",
      "You have a different, useful idea",
    ],
    suggestedResponse: "I understand why that topic is popular — I researched it too. Could we also consider my other idea so the class hears something new?",
    hint: "Acknowledge their idea first, then offer yours as an addition.",
  },

  // ── WORKPLACE ──
  {
    id: "workplace.asking-for-help",
    category: "workplace",
    difficulty: "easy",
    title: "Asking for Help",
    setting: "A quiet office on a busy morning.",
    situation: "You are stuck on a task and your colleague is free for a moment.",
    role: "You are a new colleague.",
    question: "Your colleague smiles and asks, 'How is it going?' What do you say?",
    cues: ["Your colleague seems free", "You are stuck", "The task has a clear next step"],
    suggestedResponse: "I'm a bit stuck on this report — could you help me with the numbers part when you have a minute?",
    hint: "Say what you are stuck on so the help can be specific.",
  },
  {
    id: "workplace.declining-overtime",
    category: "workplace",
    difficulty: "medium",
    title: "Saying No to Extra Hours",
    setting: "At the end of the day, your manager stops by your desk.",
    situation: "Your manager asks you to stay late, but you have plans you cannot change.",
    role: "You are an employee.",
    question: "Your manager says, 'Could you stay an extra hour tonight?' What do you say?",
    cues: [
      "Your manager is asking, not demanding",
      "You already have plans",
      "You want to stay on good terms",
    ],
    suggestedResponse: "I can't stay tonight because I have a commitment, but I can finish it first thing tomorrow — would that work?",
    hint: "Say no clearly, then offer an alternative.",
  },
  {
    id: "workplace.clarifying-feedback",
    category: "workplace",
    difficulty: "hard",
    title: "Clarifying Feedback",
    setting: "A one-to-one meeting with your supervisor.",
    situation:
      "Your supervisor says your presentation 'could be more organised', but you do not know what to change.",
    role: "You are an employee.",
    question: "Your supervisor asks, 'Do you have any questions?' What do you say?",
    cues: [
      "The feedback is vague",
      "You want to improve",
      "Asking a question shows you care",
    ],
    suggestedResponse: "Thank you for the feedback. Could you tell me which part felt least organised so I know what to work on first?",
    hint: "Turning vague feedback into a specific question helps both of you.",
  },

  // ── DAILY LIFE ──
  {
    id: "daily_life.line-jumper",
    category: "daily_life",
    difficulty: "easy",
    title: "Someone Jumps the Queue",
    setting: "A busy supermarket checkout.",
    situation:
      "Someone steps in front of you in the line without realising you were already waiting.",
    role: "You are waiting in line.",
    question: "The person starts putting items on the counter. What do you say?",
    cues: ["The person did not see you", "It is a short line", "You were clearly waiting"],
    suggestedResponse: "Excuse me — I think I was next in line. Could I go ahead?",
    hint: "A calm 'excuse me' usually fixes a small mistake.",
  },
  {
    id: "daily_life.returning-item",
    category: "daily_life",
    difficulty: "medium",
    title: "Returning an Item",
    setting: "At the returns counter of a store.",
    situation:
      "You want to return a gift that does not fit, but you lost the receipt and you are a little nervous.",
    role: "You are a customer.",
    question: "The assistant asks, 'Can I help you?' What do you say?",
    cues: [
      "You are a little nervous",
      "You lost the receipt",
      "The assistant is friendly",
    ],
    suggestedResponse: "Hi — I'd like to return this gift, but I lost the receipt. Is there anything I can do?",
    hint: "Saying what happened honestly usually gets a helpful answer.",
  },
  {
    id: "daily_life.cafeteria-seat",
    category: "daily_life",
    difficulty: "hard",
    title: "Joining a Table",
    setting: "A crowded cafeteria at lunch.",
    situation:
      "Every table is full except one where two people are sitting with free seats.",
    role: "You need somewhere to sit.",
    question: "One of the people looks up and sees you standing there. What do you say?",
    cues: [
      "The cafeteria is full",
      "There are free seats",
      "You do not know these people",
    ],
    suggestedResponse: "Hi — do you mind if I sit here? There isn't anywhere else free.",
    hint: "A polite question is a normal way to join an open seat.",
  },

  // ── RELATIONSHIPS ──
  {
    id: "relationships.friend-upset",
    category: "relationships",
    difficulty: "easy",
    title: "A Friend Seems Upset",
    setting: "Walking home from school with a friend.",
    situation:
      "Your friend is quieter than usual and keeps looking at the ground.",
    role: "You are a friend.",
    question: "Your friend finally says, 'I'm okay, really.' What do you say?",
    cues: [
      "Your friend is quieter than usual",
      "They are not making eye contact",
      "They said 'okay' but seem low",
    ],
    suggestedResponse: "You don't have to talk about it, but I'm here if you want to. We can just walk if that helps.",
    hint: "Offering to listen without pushing is very kind.",
  },
  {
    id: "relationships.sibling-borrows",
    category: "relationships",
    difficulty: "medium",
    title: "A Sibling Borrows Your Things",
    setting: "At home, your sibling is holding your new headphones.",
    situation:
      "Your sibling took your headphones without asking, and this is not the first time.",
    role: "You are the sibling.",
    question: "Your sibling says, 'Can I borrow these for the day?' What do you say?",
    cues: [
      "This has happened before",
      "You care about your things",
      "You still want to get along",
    ],
    suggestedResponse: "I don't love that you took them without asking. Please ask first next time — and yes, you can borrow them today.",
    hint: "You can say how you feel and still be generous.",
  },
  {
    id: "relationships.relative-questions",
    category: "relationships",
    difficulty: "hard",
    title: "A Personal Question",
    setting: "A family dinner with a relative you see rarely.",
    situation:
      "A relative keeps asking questions about your grades that you do not want to discuss.",
    role: "You are at the family dinner.",
    question: "The relative asks, 'So, why are your grades not better?' What do you say?",
    cues: [
      "The question feels personal",
      "You want to stay polite",
      "You do not have to explain yourself",
    ],
    suggestedResponse: "I'd rather not talk about my grades tonight — but I'm happy to chat about something else.",
    hint: "You can politely change the subject without explaining yourself.",
  },
]);

/** Normalize a difficulty id; unknown values fall back to "easy". */
export function normalizeDifficulty(difficulty) {
  return SCENARIO_DIFFICULTY_IDS.includes(difficulty) ? difficulty : "easy";
}

/** Normalize a category id; unknown values fall back to "daily_life". */
export function normalizeCategory(category) {
  return SCENARIO_CATEGORY_IDS.includes(category) ? category : "daily_life";
}

function slugify(value) {
  return String(value ?? "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
}

/**
 * Build the config the UI + generators share.
 * @param {{ category?: string, difficulty?: string, signals?: object,
 *           variantSeed?: number }} input
 */
export function buildScenarioConfig({
  category = "daily_life",
  difficulty = "easy",
  signals = {},
  variantSeed = 0,
} = {}) {
  const normalizedCategory = normalizeCategory(category);
  const normalizedDifficulty = normalizeDifficulty(difficulty);
  return {
    category: normalizedCategory,
    categoryLabel: getScenarioCategoryById(normalizedCategory)?.label ?? "Daily Life",
    difficulty: normalizedDifficulty,
    difficultyLabel: getScenarioDifficultyById(normalizedDifficulty)?.label ?? "Easy",
    hintsEnabled: Boolean(signals.provideHints),
    reducedCues: Boolean(signals.simplify || signals.reduceDistractions),
    slowPace: Boolean(signals.slowPace),
    variantSeed: Number.isFinite(variantSeed) ? Math.abs(variantSeed) : 0,
  };
}

/** Pick a deterministic fallback scenario, rotating by variantSeed so repeated
 *  sessions do not repeat the same exercise when AI is unavailable. */
export function getFallbackScenario(config = {}) {
  const category = normalizeCategory(config.category);
  let pool = FALLBACK_SCENARIOS.filter((scenario) => scenario.category === category);
  if (pool.length === 0) pool = [...FALLBACK_SCENARIOS];
  const index = (config.variantSeed ?? 0) % pool.length;
  return {
    ...pool[index],
    category,
    difficulty: normalizeDifficulty(config.difficulty),
    source: "fallback",
  };
}

/**
 * Normalize an AI scenario into the module's contract. Returns null when the
 * AI output is not usable so the caller can fall back safely.
 */
export function normalizeScenario(raw, config = {}) {
  if (!raw || typeof raw !== "object") return null;
  const cues = Array.isArray(raw.cues)
    ? raw.cues.map((cue) => String(cue ?? "").trim()).filter(Boolean).slice(0, 4)
    : [];
  const situation = String(raw.situation ?? "").trim();
  const question = String(raw.question ?? "").trim();
  const suggestedResponse = String(raw.suggestedResponse ?? "").trim();
  if (!situation || !question || !suggestedResponse || cues.length === 0) return null;

  const category = normalizeCategory(raw.category ?? config.category);
  return {
    id: String(raw.id ?? "").trim() || `${slugify(raw.title) || "scenario"}-${config.variantSeed ?? 0}`,
    category,
    difficulty: normalizeDifficulty(raw.difficulty ?? config.difficulty),
    title: String(raw.title ?? "Social scenario").trim(),
    setting: String(raw.setting ?? "").trim(),
    situation,
    role: String(raw.role ?? "").trim(),
    question,
    cues,
    suggestedResponse,
    hint: String(raw.hint ?? "").trim() || null,
    source: "ai",
  };
}

/**
 * Generate a scenario for the simulator. Uses Gemini through the shared AI
 * facade when available; otherwise returns a deterministic fallback. Never
 * throws.
 * @returns {{ scenario: object, aiAvailable: boolean, source: "ai"|"fallback" }}
 */
export async function generateScenario(config, { apiKey } = {}) {
  try {
    const generated = await callAiGenerateScenario({ config, apiKey });
    const scenario = normalizeScenario(generated, config);
    if (scenario) {
      return { scenario, aiAvailable: true, source: "ai" };
    }
  } catch {
    // fall through to the deterministic pool
  }
  return { scenario: getFallbackScenario(config), aiAvailable: false, source: "fallback" };
}

// ─────────────────────────────────────────────
//  Attempt history (scores + titles only, never transcripts)
// ─────────────────────────────────────────────
function normalizeUserId(userId) {
  return userId ? String(userId) : null;
}

function attemptsStorageKey(userId) {
  return `${SCENARIO_ATTEMPTS_STORAGE_KEY}_${normalizeUserId(userId) ?? "guest"}`;
}

function readAttempts(userId) {
  try {
    const raw = localStorage.getItem(attemptsStorageKey(userId));
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function writeAttempts(userId, attempts) {
  try {
    localStorage.setItem(attemptsStorageKey(userId), JSON.stringify(attempts));
  } catch {
    // private mode / quota — history simply won't persist
  }
  return attempts;
}

/** Record a completed single-response practice round. Stores no transcripts. */
export function recordScenarioAttempt(
  userId,
  { scenario, evaluation, response, voiceUsed = false, now = Date.now() } = {},
) {
  if (!scenario) return readAttempts(userId);
  const record = {
    id: `attempt-${now}-${Math.random().toString(36).slice(2, 8)}`,
    scenarioId: scenario.id,
    title: scenario.title ?? "",
    category: scenario.category ?? null,
    difficulty: scenario.difficulty ?? null,
    score: evaluation?.score ?? null,
    strengths: Array.isArray(evaluation?.strengths) ? evaluation.strengths.slice(0, 3) : [],
    voiceUsed: Boolean(voiceUsed),
    usedAi: evaluation?.usedAi === true,
    completedAt: new Date(now).toISOString(),
  };
  const attempts = [record, ...readAttempts(userId)].slice(0, 60);
  return writeAttempts(userId, attempts);
}

export function listScenarioAttempts(userId, { limit } = {}) {
  const attempts = [...readAttempts(userId)].sort((a, b) =>
    String(b.completedAt ?? "").localeCompare(String(a.completedAt ?? "")),
  );
  return Number.isInteger(limit) && limit > 0 ? attempts.slice(0, limit) : attempts;
}

export function getScenarioAttemptStats(userId) {
  const attempts = readAttempts(userId);
  const scores = attempts.filter((attempt) => Number.isFinite(attempt.score)).map((attempt) => attempt.score);
  return {
    totalAttempts: attempts.length,
    averageScore: scores.length > 0 ? Math.round(scores.reduce((sum, score) => sum + score, 0) / scores.length) : null,
  };
}

export { SOCIAL_SCENARIO_MODULE_ID };
