import { FEATURES } from "@/lib/featureRegistry";
import { DISORDERS } from "@/lib/disorders";
import {
  ModuleCategory,
  PrivacyLevel,
  SafetyLevel,
  validateSupportModuleDefinition,
} from "@/support/schemas/supportSchemas";

const rawSupportModules = [
  {
    id: "support.task_breakdown",
    moduleId: "support.task_breakdown",
    title: "Task Breakdown",
    description: "Split large tasks into guided steps.",
    category: ModuleCategory.EXECUTIVE,
    interventionTypes: ["task_breakdown", "planning_support"],
    route: "/adhd/breakdown",
    tags: ["overwhelm", "planning", "task_start", "working_memory"],
    disorders: [],
    expectedOutcomeMetrics: ["steps_created", "steps_completed", "duration_ms"],
    developmentDomain: "adhd",
    supportedNeeds: ["task_initiation", "task_simplification", "attention_support"],
    potentiallyRelevantDomains: ["adhd", "asd", "anxiety", "dyspraxia", "general"],
    actions: ["generate", "edit", "reorder", "start", "complete", "abandon"],
    configurableParameters: { style: true, priority: true, timerMinutes: true },
    launchPolicy: "user_initiated",
    lifecycleEvents: ["shown", "started", "progressed", "completed", "abandoned", "rated"],
    outcomeFields: ["steps_created", "steps_completed", "duration_ms", "rating"],
    legacyIds: [FEATURES.ADHD_BREAKDOWN],
  },
  {
    id: "support.focus_session",
    moduleId: "support.focus_session",
    title: "Focus Session",
    description: "Use timed focus blocks with reset cues.",
    category: ModuleCategory.EXECUTIVE,
    interventionTypes: ["focus_session", "attention_support"],
    route: "/adhd/focus",
    tags: ["focus", "distraction", "task_switching", "time_blindness"],
    disorders: [],
    expectedOutcomeMetrics: ["session_minutes", "completed_blocks", "interruptions"],
    developmentDomain: "adhd",
    supportedNeeds: ["attention_support", "task_initiation", "stress_reduction"],
    potentiallyRelevantDomains: ["adhd", "anxiety", "asd", "depression", "general"],
    actions: ["start", "pause", "resume", "reset", "complete", "abandon"],
    configurableParameters: { mode: true, durationMinutes: true, intent: true, tag: true },
    launchPolicy: "user_initiated",
    lifecycleEvents: ["shown", "started", "progressed", "completed", "abandoned", "rated"],
    outcomeFields: ["session_minutes", "completed_blocks", "interruptions", "rating"],
    legacyIds: [FEATURES.ADHD_FOCUS],
  },
  {
    id: "support.mood_checkin",
    moduleId: "support.mood_checkin",
    title: "Mood Check-in",
    description: "Use structured prompts for emotional regulation.",
    category: ModuleCategory.EMOTIONAL,
    interventionTypes: ["grounding", "emotion_regulation", "calming"],
    route: "/adhd/emotion-coach",
    tags: ["panic", "stress", "emotion_regulation", "overwhelm"],
    disorders: [],
    expectedOutcomeMetrics: ["before_level", "after_level", "duration_ms"],
    safetyLevel: SafetyLevel.CAUTION,
    repetitionLimit: { maxCount: 4, windowHours: 24 },
    developmentDomain: "adhd",
    supportedNeeds: ["emotional_awareness", "emotional_regulation", "stress_reduction"],
    potentiallyRelevantDomains: ["adhd", "anxiety", "asd", "depression", "general"],
    actions: ["check_in", "select_strategy", "complete", "abandon"],
    configurableParameters: { mood: true, note: true },
    launchPolicy: "user_initiated",
    lifecycleEvents: ["shown", "started", "completed", "abandoned", "rated"],
    outcomeFields: ["before_level", "after_level", "duration_ms", "rating"],
    legacyIds: [FEATURES.ADHD_EMOTION],
  },
  {
    id: "support.visual_timeline",
    moduleId: "support.visual_timeline",
    title: "Visual Timeline",
    description: "Organize tasks and routines with time-aware visual blocks.",
    category: ModuleCategory.EXECUTIVE,
    interventionTypes: ["visual_timeline", "routine_support", "time_management"],
    route: "/adhd/timeline",
    tags: ["time_blindness", "planning", "routine", "task_start"],
    disorders: [],
    expectedOutcomeMetrics: ["blocks_created", "blocks_completed", "duration_ms"],
    developmentDomain: "adhd",
    supportedNeeds: ["time_management", "routine_support", "task_initiation"],
    potentiallyRelevantDomains: ["adhd", "asd", "depression", "dyspraxia", "general"],
    actions: ["add_block", "start", "complete", "snooze", "abandon"],
    configurableParameters: { density: true, reminders: true, date: true },
    launchPolicy: "user_initiated",
    lifecycleEvents: ["shown", "started", "progressed", "completed", "abandoned"],
    outcomeFields: ["blocks_created", "blocks_completed", "duration_ms"],
    legacyIds: [FEATURES.ADHD_TIMELINE],
  },
  {
    id: "support.accountability_session",
    moduleId: "support.accountability_session",
    title: "Accountability Session",
    description: "Use a guided accountability session to begin or continue a task.",
    category: ModuleCategory.EXECUTIVE,
    interventionTypes: ["accountability_session", "task_initiation"],
    route: "/adhd/doubling",
    tags: ["task_start", "focus", "planning", "accountability"],
    disorders: [],
    expectedOutcomeMetrics: ["duration_ms", "commitment_met", "rating"],
    developmentDomain: "adhd",
    supportedNeeds: ["task_initiation", "attention_support", "social_connection"],
    potentiallyRelevantDomains: ["adhd", "depression", "anxiety", "general"],
    actions: ["start", "end", "complete", "abandon"],
    configurableParameters: { commitment: true, durationMinutes: true },
    launchPolicy: "confirmation_required",
    lifecycleEvents: ["shown", "started", "progressed", "completed", "abandoned", "rated"],
    outcomeFields: ["duration_ms", "commitment_met", "rating"],
    legacyIds: [FEATURES.ADHD_DOUBLING],
  },
  {
    id: FEATURES.OCD_HIERARCHY,
    title: "Exposure Hierarchy Builder",
    description: "Create graded exposure steps for structured practice.",
    category: ModuleCategory.SPECIALIZED,
    interventionTypes: ["exposure_planning", "erp_hierarchy"],
    route: "/ocd/exposure-hierarchy",
    tags: ["exposure", "fear", "avoidance", "uncertainty"],
    disorders: [DISORDERS.OCD],
    expectedOutcomeMetrics: ["items_created", "difficulty_range"],
    safetyLevel: SafetyLevel.CAUTION,
  },
  {
    id: FEATURES.OCD_SESSION_TIMER,
    title: "Exposure Session Timer",
    description: "Time exposure practice with non-reassurance prompts.",
    category: ModuleCategory.SPECIALIZED,
    interventionTypes: ["erp_exposure", "response_prevention"],
    route: "/ocd/exposure-session",
    tags: ["exposure", "avoidance", "urge_control", "uncertainty"],
    disorders: [DISORDERS.OCD],
    expectedOutcomeMetrics: ["pre_suds", "post_suds", "duration_ms"],
    safetyLevel: SafetyLevel.CAUTION,
  },
  {
    id: FEATURES.OCD_SUDS,
    title: "SUDS Monitor",
    description: "Track distress level during a support activity.",
    category: ModuleCategory.SPECIALIZED,
    interventionTypes: ["suds_tracking", "distress_monitoring"],
    route: "/ocd/suds-monitor",
    tags: ["anxiety", "monitoring", "exposure"],
    disorders: [DISORDERS.OCD, DISORDERS.ANXIETY],
    expectedOutcomeMetrics: ["suds_level", "timestamp"],
    safetyLevel: SafetyLevel.CAUTION,
    repetitionLimit: { maxCount: 6, windowHours: 24 },
  },
  {
    id: FEATURES.ASD_SENSORY,
    title: "Sensory Regulation",
    description: "Adjust sensory load and access calming supports.",
    category: ModuleCategory.SENSORY,
    interventionTypes: ["sensory_regulation", "low_stimulation"],
    route: "/asd/sensory",
    tags: ["sensory_overload", "overwhelm", "stress_reactivity"],
    disorders: [DISORDERS.ASD, DISORDERS.ANXIETY],
    expectedOutcomeMetrics: ["trigger", "before_level", "after_level"],
    safetyLevel: SafetyLevel.CAUTION,
  },
  {
    id: FEATURES.ASD_MELTDOWN,
    title: "Meltdown Prevention",
    description: "Use a low-stimulation workflow during overload risk.",
    category: ModuleCategory.SENSORY,
    interventionTypes: ["overload_support", "meltdown_prevention"],
    route: "/asd/meltdown",
    tags: ["panic", "overwhelm", "sensory_overload"],
    disorders: [DISORDERS.ASD, DISORDERS.ANXIETY],
    expectedOutcomeMetrics: ["risk_level", "steps_completed"],
    safetyLevel: SafetyLevel.CAUTION,
  },
  {
    id: "dyslexia.adaptive-reading",
    title: "Adaptive Reading",
    description: "Practice guided reading with adaptive pacing.",
    category: ModuleCategory.LEARNING,
    interventionTypes: ["adaptive_reading", "reading_support"],
    route: "/dyslexia/adaptive-reading",
    tags: ["reading_fatigue", "focus", "processing_load"],
    disorders: [DISORDERS.DYSLEXIA],
    expectedOutcomeMetrics: ["read_time_ms", "struggles", "adjustments"],
  },
  {
    id: FEATURES.DYSLEXIA_ADAPTIVE_READING,
    title: "Adaptive Reading Module",
    description: "Use accessibility controls, TTS, and reading focus tools.",
    category: ModuleCategory.LEARNING,
    interventionTypes: ["adaptive_reading", "tts_support", "reading_accessibility"],
    route: "/dyslexia/adaptive-reading",
    tags: ["reading_fatigue", "tts", "accessibility", "focus"],
    disorders: [DISORDERS.DYSLEXIA, DISORDERS.APD],
    expectedOutcomeMetrics: ["tts_activations", "word_taps", "adjustments"],
  },
  {
    id: "dyscalculia.step-practice",
    title: "Guided Step Practice",
    description: "Solve math with structured step-by-step guidance.",
    category: ModuleCategory.LEARNING,
    interventionTypes: ["math_step_practice", "scaffolded_learning"],
    route: "/dyscalculia/step-practice",
    tags: ["step_support", "working_memory", "number_confusion"],
    disorders: [DISORDERS.DYSCALCULIA],
    expectedOutcomeMetrics: ["accuracy", "hesitation_ms", "scaffold_level"],
  },
  {
    id: "dyscalculia.calm-mode",
    title: "Calm Mode",
    description: "Reduce pressure during difficult number tasks.",
    category: ModuleCategory.EMOTIONAL,
    interventionTypes: ["math_calm_mode", "calming"],
    route: "/dyscalculia/calm-mode",
    tags: ["number_anxiety", "stress", "overwhelm"],
    disorders: [DISORDERS.DYSCALCULIA, DISORDERS.ANXIETY],
    expectedOutcomeMetrics: ["before_level", "after_level", "exit_count"],
    safetyLevel: SafetyLevel.CAUTION,
  },
  {
    id: "support.cognitive_reframing",
    moduleId: "support.cognitive_reframing",
    title: "Cognitive Reframing",
    description: "Use structured prompts to examine difficult thoughts.",
    category: ModuleCategory.EMOTIONAL,
    interventionTypes: ["cognitive_reframe", "thought_support"],
    route: "/depression/reality",
    tags: ["rumination", "intrusive_thoughts", "low_mood"],
    disorders: [],
    expectedOutcomeMetrics: ["reframe_completed", "before_level", "after_level"],
    safetyLevel: SafetyLevel.CAUTION,
    developmentDomain: "depression",
    supportedNeeds: ["cognitive_reframing", "low_mood_support", "anxiety_reduction"],
    potentiallyRelevantDomains: ["depression", "anxiety", "adhd", "general"],
    actions: ["analyze", "select_reframe", "complete", "abandon"],
    configurableParameters: { thought: true, reframeStyle: true },
    launchPolicy: "confirmation_required",
    lifecycleEvents: ["shown", "started", "completed", "abandoned", "rated"],
    outcomeFields: ["reframe_completed", "before_level", "after_level", "rating"],
    legacyIds: [FEATURES.DEPRESSION_REALITY],
  },
  {
    id: "support.gentle_activity",
    moduleId: "support.gentle_activity",
    title: "Gentle Activity",
    description: "Use structured regulation and activation guidance.",
    category: ModuleCategory.EMOTIONAL,
    interventionTypes: ["behavioral_activation", "daily_momentum"],
    route: "/depression/mvh",
    tags: ["low_mood", "low_energy", "stability"],
    disorders: [],
    expectedOutcomeMetrics: ["steps_completed", "energy_before", "energy_after"],
    safetyLevel: SafetyLevel.CAUTION,
    developmentDomain: "depression",
    supportedNeeds: ["low_mood_support", "low_energy_support", "routine_support"],
    potentiallyRelevantDomains: ["depression", "adhd", "anxiety", "general"],
    actions: ["start", "advance_step", "complete", "abandon"],
    configurableParameters: { activityLevel: true, pacing: true },
    launchPolicy: "user_initiated",
    lifecycleEvents: ["shown", "started", "progressed", "completed", "abandoned", "rated"],
    outcomeFields: ["steps_completed", "energy_before", "energy_after", "rating"],
    legacyIds: [FEATURES.DEPRESSION_MVH],
  },
  {
    id: "support.grounding",
    moduleId: "support.grounding",
    title: "Grounding",
    description: "Use timed grounding techniques to lower anxiety intensity.",
    category: ModuleCategory.EMOTIONAL,
    interventionTypes: ["grounding", "anxiety_reduction"],
    route: "/depression/anxietydissolver",
    tags: ["panic", "stress", "anxiety", "emotion_regulation"],
    disorders: [],
    expectedOutcomeMetrics: ["before_level", "after_level", "duration_ms"],
    safetyLevel: SafetyLevel.CAUTION,
    developmentDomain: "depression",
    supportedNeeds: ["stress_reduction", "anxiety_reduction", "emotional_regulation"],
    potentiallyRelevantDomains: ["depression", "anxiety", "adhd", "asd", "general"],
    actions: ["start", "pause", "resume", "complete", "abandon"],
    configurableParameters: { technique: true, durationMinutes: true },
    launchPolicy: "user_initiated",
    lifecycleEvents: ["shown", "started", "completed", "abandoned", "rated"],
    outcomeFields: ["before_level", "after_level", "duration_ms", "rating"],
    legacyIds: [FEATURES.DEPRESSION_ANXIETY_DISSOLVER],
  },
  {
    id: "support.social_connection",
    moduleId: "support.social_connection",
    title: "Social Connection",
    description: "Use guided outreach prompts to reconnect with others.",
    category: ModuleCategory.EMOTIONAL,
    interventionTypes: ["social_connection", "outreach_support"],
    route: "/depression/social",
    tags: ["social_stress", "low_mood", "connection"],
    disorders: [],
    expectedOutcomeMetrics: ["outreach_action", "rating"],
    safetyLevel: SafetyLevel.CAUTION,
    developmentDomain: "depression",
    supportedNeeds: ["social_connection", "low_mood_support"],
    potentiallyRelevantDomains: ["depression", "anxiety", "adhd", "general"],
    actions: ["select_template", "copy_message", "complete", "dismiss"],
    configurableParameters: { template: true, status: true },
    launchPolicy: "confirmation_required",
    lifecycleEvents: ["shown", "started", "completed", "dismissed", "rated"],
    outcomeFields: ["outreach_action", "rating"],
    legacyIds: [FEATURES.DEPRESSION_SOCIAL],
  },
  {
    id: "support.evidence_journal",
    moduleId: "support.evidence_journal",
    title: "Evidence Journal",
    description: "Retain user-approved evidence entries in a private local journal.",
    category: ModuleCategory.EMOTIONAL,
    interventionTypes: ["evidence_journal", "structured_reflection"],
    route: "/depression/evidence",
    tags: ["reflection", "self_support"], disorders: [],
    expectedOutcomeMetrics: ["entries_saved", "rating"], safetyLevel: SafetyLevel.CAUTION,
    developmentDomain: "depression", supportedNeeds: ["cognitive_reframing", "low_mood_support"], potentiallyRelevantDomains: ["depression", "anxiety", "general"],
    actions: ["save_entry", "complete", "abandon"], configurableParameters: { category: true }, launchPolicy: "confirmation_required",
    lifecycleEvents: ["shown", "started", "progressed", "completed", "abandoned", "rated"], outcomeFields: ["entries_saved", "rating"], legacyIds: [],
  },
];

export const SUPPORT_MODULES = rawSupportModules.map((module) =>
  validateSupportModuleDefinition({
    privacyDefault: PrivacyLevel.PRIVATE,
    safetyLevel: SafetyLevel.STANDARD,
    supportedRoles: ["user"],
    repetitionLimit: { maxCount: 2, windowHours: 24 },
    ...module,
  }),
);

export const SUPPORT_MODULE_LOOKUP = SUPPORT_MODULES.reduce((acc, module) => {
  acc[module.id] = module;
  module.legacyIds.forEach((legacyId) => {
    acc[legacyId] = module;
  });
  return acc;
}, {});

export function getSupportModules() {
  return [...SUPPORT_MODULES];
}

export function getSupportModuleById(moduleId) {
  return SUPPORT_MODULE_LOOKUP[moduleId] ?? null;
}

export function getCanonicalSupportModuleId(moduleId) {
  return getSupportModuleById(moduleId)?.id ?? null;
}

export function getSupportModulesByInterventionType(interventionType) {
  return SUPPORT_MODULES.filter((module) => module.interventionTypes.includes(interventionType));
}

export function getSupportModulesByRoute(route) {
  return SUPPORT_MODULES.filter((module) => module.route === route);
}

